services:
  php83_fpm_example:
    container_name: 'php83_fpm_example'
    build:
      context: '../../php8.3-fpm'
      # context: 'https://github.com/wsp-repo/dockers.git#:php8.3-fpm'
    volumes:
      - './configs/php/:/opt/php/conf/'
      - './configs/cron/:/opt/cron/conf/'
      - './configs/ssmtp/:/opt/ssmtp/conf/'
      - './sources/htdocs/:/www/htdocs/'
      - './sources/log/ssmtp/:/var/log/ssmtp/'
      - './sources/log/cron/:/var/log/cron/'
      - './sources/log/php/:/var/log/php/'
    ports:
      # поменять порт для хоста
      - '127.0.0.1:9082:9000'
    extra_hosts:
      - 'mysql:192.168.0.1'
    restart: 'always'
networks:
  default:
    name: php83_fpm_example
